site_name: RedTeam subnet - Blog
site_description: "This is a short description of the project."
site_url: https://blog.theredteam.io
repo_name: RedTeamSubnet
repo_url: https://github.com/RedTeamSubnet
extra_css:
  - assets/css/custom.css
  - assets/css/colors.css
theme:
  name: material
  # name: readthedocs
  language: en
  custom_dir: overrides
  font:
    text: Public Sans
    code: JetBrains Mono
  logo: assets/images/logo.light.svg
  favicon: assets/images/logo.dark.svg
  icon:
    # logo: fontawesome/brands/python
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    # - navigation.sections
    # - navigation.expand
    # - navigation.instant
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/tex-mml-chtml.js
plugins:
  - meta
  - tags
  - search
  # - awesome-nav:
  #     expand: true
  - mkdocstrings
  # - blog:
  #     blog_dir: blog
  #     post_dir: "{blog}/posts"
  #     post_date_format: medium
  #     post_url_format: "{slug}"
  #     pagination: false
  #     categories_allowed:
  #       - Top Submissions
  #       - Challenges
  #       - Tutorials
  #       - Security Research
  #       - News
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RedTeamSubnet
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/redteamsubnet61
    - icon: fontawesome/solid/house
      link: https://www.theredteam.io/
    # - icon: fontawesome/brands/x-twitter
    #   link: https://x.com/abdibekbolot
    - icon: fontawesome/solid/chart-line
      link: https://dashboard.theredteam.io/
    - icon: fontawesome/solid/book
      link: https://docs.theredteam.io/
copyright: Copyright &copy; 2025 - RedTeam
nav:
  - Home: index.md
  - Important: important/index.md
  - Announcements: announcements/index.md
  - Blog: blog/index.md
