authors:
  oscar:
    name: Oscar
    avatar: https://avatars.githubusercontent.com/ohayek
    url: https://github.com/ohayek
  javokhir:
    name: Javokhir
    avatar: https://avatars.githubusercontent.com/aliyuldashev
    url: https://github.com/aliyuldashev
  bekbolot:
    name: Bekbolot
    avatar: https://avatars.githubusercontent.com/abdibekbolot
    url: https://github.com/abdibekbolot
